server:
  port: 8088
  shutdown: graceful

mybatis:
  mapper-locations: classpath*:META-INF/persistence/mybatis/mapper/**/*.xml
  type-aliases-package: com.dk.template.sqlitejpa.domain.**.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true
    call-setters-on-nulls: true
    jdbc-type-for-null: null

spring:
  jpa:
    database-platform: com.dk.template.sqlitejpa.SQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:sqlite:sqlitesample.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin
    initialization-mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
